typography_spectrum: 0.9206673337612301
color:
  brandStrength: 0.46022344939410686
  lightness: 0.02596130082383752
  saturation: 0.09888794249854982
  rhythmicContrast: 0.758610290242359
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.22994635137729347
author:
  name: Max McChesney
  email: max@digitalcrafts.com
  url: www.DigitalCrafts.com
name: Max McChesney
title: Along The Way
description: 'Lessons learned on tech, start-ups, programming, and sales.'
